### ISSUE TITLE
TLS does not provide non-repudiation

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-wp3-information-security#1]
One of the security issues mentioned in @erasmus-without-paper/wp3's *Information Security* document is [non-repudiation](https://en.wikipedia.org/wiki/Non-repudiation).

[Version 0.1a](https://github.com/erasmus-without-paper/ewp-wp3-information-security/blob/v0.1a/information-security.docx) of this document [implies](https://cloud.githubusercontent.com/assets/2168535/21609189/4bfabf88-d1c1-11e6-90e9-1f66c7dce1da.png) that TLS provides non-repudiation, which is not true. Of course, non-repudiation can be provided in EWP by putting digital signatures in proper places, but TLS itself does not provide it (without additional help, such as keeping an archive of network data dumps).

Note: This issue is only about a minor inaccuracy in the *Information Security* document. It's not about providing non-repudiation in key EWP scenarios. We have separate issues in GitHub about such topics, e.g. about the option of providing non-repudiation in Mobilties API's `<timeline>` element (see [here](https://github.com/erasmus-without-paper/ewp-specs-api-mobilities/issues/5#issuecomment-268913671)).

**Comment by wrygiel** [comment]
Not sure who handles this document right now. Could you verify if this issue is fixed?

**Comment by janinamincer-daszkiewicz** [comment]
TLS has been discontinued.
